#!/bin/bash

export PGHOST="dbserver"
export PGPORT="5432"
export PGDATABASE="brazda_test"
export PGPASSWORD="Bitov7+Sv8b"

echo "Ruším starou databázi BRAZDA..."
/usr/bin/dropdb -h $PGHOST -p $PGPORT -U postgres $PGDATABASE

echo "Vytvářím novou databázi BRAZDA..."
/usr/bin/createdb -h $PGHOST -p $PGPORT -U postgres -O brazda -E UTF8 -T template0 $PGDATABASE
if [ $? -gt 0 ]; then exit; fi

DIR="$(dirname "$0")"
source "$DIR/config"

echo ""
echo "Importuji schéma..."
/usr/bin/psql -q -h $PGHOST -p $PGPORT -f schema.sql
if [ $? -gt 0 ]; then exit; fi

echo "Importuji základní data..."
/usr/bin/psql -q -h $PGHOST -p $PGPORT -f data.sql
if [ $? -gt 0 ]; then exit; fi

echo "Aplikuji patch 001..."
/usr/bin/psql -q -h $PGHOST -p $PGPORT -f p001.sql
if [ $? -gt 0 ]; then exit; fi

echo "Aplikuji patch 002..."
/usr/bin/psql -q -h $PGHOST -p $PGPORT -f p002.sql
if [ $? -gt 0 ]; then exit; fi

echo "Aplikuji patch 003..."
/usr/bin/psql -q -h $PGHOST -p $PGPORT -f p003.sql
if [ $? -gt 0 ]; then exit; fi

echo "Aplikuji patch 004..."
/usr/bin/psql -q -h $PGHOST -p $PGPORT -f p004.sql
if [ $? -gt 0 ]; then exit; fi

echo "Aplikuji patch 005..."
/usr/bin/psql -q -h $PGHOST -p $PGPORT -f p005.sql
if [ $? -gt 0 ]; then exit; fi

echo "Aplikuji patch 006..."
/usr/bin/psql -q -h $PGHOST -p $PGPORT -f p006.sql
if [ $? -gt 0 ]; then exit; fi

echo "Aplikuji patch 007..."
/usr/bin/psql -q -h $PGHOST -p $PGPORT -f p007.sql
if [ $? -gt 0 ]; then exit; fi

echo "Aplikuji patch 008..."
/usr/bin/psql -q -h $PGHOST -p $PGPORT -f p008.sql
if [ $? -gt 0 ]; then exit; fi

echo "Aplikuji patch 009..."
/usr/bin/psql -q -h $PGHOST -p $PGPORT -f p009.sql
if [ $? -gt 0 ]; then exit; fi

echo "Aplikuji patch 010..."
/usr/bin/psql -q -h $PGHOST -p $PGPORT -f p010.sql
if [ $? -gt 0 ]; then exit; fi

echo "Aplikuji patch 011..."
/usr/bin/psql -q -h $PGHOST -p $PGPORT -f p011.sql
if [ $? -gt 0 ]; then exit; fi

echo "Aplikuji patch 012..."
/usr/bin/psql -q -h $PGHOST -p $PGPORT -f p012.sql
if [ $? -gt 0 ]; then exit; fi

echo "Aplikuji patch 013..."
/usr/bin/psql -q -h $PGHOST -p $PGPORT -f p013.sql
if [ $? -gt 0 ]; then exit; fi

echo "Aplikuji patch 014..."
/usr/bin/psql -q -h $PGHOST -p $PGPORT -f p014.sql
if [ $? -gt 0 ]; then exit; fi

echo "Aplikuji patch 015..."
/usr/bin/psql -q -h $PGHOST -p $PGPORT -f p015.sql
if [ $? -gt 0 ]; then exit; fi

echo "Aplikuji patch 016..."
/usr/bin/psql -q -h $PGHOST -p $PGPORT -f p016.sql
if [ $? -gt 0 ]; then exit; fi

echo "Aplikuji patch 017..."
/usr/bin/psql -q -h $PGHOST -p $PGPORT -f p017.sql
if [ $? -gt 0 ]; then exit; fi

echo "Aplikuji patch 018..."
/usr/bin/psql -q -h $PGHOST -p $PGPORT -f p018.sql

echo "Aplikuji patch 019..."
/usr/bin/psql -q -h $PGHOST -p $PGPORT -f p019.sql

if [ $? -gt 0 ]; then exit; fi
echo "Importuji základní data..."
/usr/bin/psql -q -h $PGHOST -p $PGPORT -f default.sql
if [ $? -gt 0 ]; then exit; fi

echo 'Hotovo!'
