#!/bin/bash

DIR="$(dirname "$0")"
source "$DIR/config"

PGHOST="127.0.0.1"

echo "Generating database documentation for database '$PGDATABASE'..."
java -jar schemaSpy_5.0.0.jar \
	-t pgsql \
	-dp /usr/share/jdbc-postgresql/lib/jdbc-postgresql.jar \
	-host $PGHOST \
	-db $PGDATABASE \
	-u $PGUSER \
	-p $PGPASSWORD \
	-s public \
	-o ../doc/db

if [ $? -ne 0 ]; then
	echo -e "\nPokud si schemaSpy stěžuje, že nemůže najít JDBC ovladač,\nje potřeba jej doinstalovat (dev-java/jdbc-postgresql).\nPro svůj běh potřebuje rovněž GraphViz (media-gfx/graphviz)."
fi
